"""add promo codes

Revision ID: 3e9349f3816f
Revises: 812874b79ca9
Create Date: 2025-12-21 15:08:32.292451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9349f3816f'
down_revision: Union[str, Sequence[str], None] = '812874b79ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('generations', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    # op.alter_column('style_prompts', 'description',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=512),
    #            existing_nullable=False)
    # op.alter_column('style_prompts', 'prompt',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=2048),
    #            existing_nullable=False)
    op.drop_index(op.f('ix_style_prompts_usage_count'), table_name='style_prompts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_style_prompts_usage_count'), 'style_prompts', ['usage_count'], unique=False)
    op.alter_column('style_prompts', 'prompt',
               existing_type=sa.String(length=2048),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('style_prompts', 'description',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
