"""init

Revision ID: 93773858a74e
Revises: 
Create Date: 2025-12-19 14:41:17.960728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93773858a74e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('style_prompts', 'description',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=512),
    #            existing_nullable=False)
    # op.alter_column('style_prompts', 'prompt',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=2048),
    #            existing_nullable=False)
    # ### end Alembic commands ###
    ...

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('style_prompts', 'prompt',
               existing_type=sa.String(length=2048),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('style_prompts', 'description',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
